# https://taskfile.dev
version: "3"

tasks:
  install-rustup:
    status:
      - which rustup
    cmds:
      - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
  install-nightly-rust:
    status:
      - rustc --version | grep nightly
    cmds:
      - task: install-rustup
      - rustup toolchain install nightly --target thumbv7em-none-eabihf
  install-target:
    cmds:
      - task: install-rustup
      - rustup target install thumbv7em-none-eabihf
  install-hf2:
    status:
      - which hf2
    cmds:
      - cargo install hf2-cli
  flash:
    desc: "Flash to pybadge the runtime with a game bundled in"
    cmds:
      - task: install-nightly-rust
      - task: install-target
      - task: install-hf2
      - test {{.CLI_ARGS}}
      - test -f {{.CLI_ARGS}}
      - GAME_PATH={{.CLI_ARGS}} cargo run --release
