# https://taskfile.dev
version: "3"

tasks:
  build-wasm:
    sources:
      - snake/main.wat
    status:
      - test -f snake.wasm
    cmds:
      - wat2wasm -o snake.wasm snake/main.wat
      - >
        wasm-opt
        -Oz --zero-filled-memory --strip-producers
        snake.wasm -o snake.wasm
  flash:
    desc: "Flash the demo to pybadge"
    cmds:
      - task: build-wasm
      - test {{.CLI_ARGS}}
      - test -f {{.CLI_ARGS}}
      - GAME_PATH={{.CLI_ARGS}} cargo run --release
