# https://taskfile.dev
version: "3"

tasks:
  build-wasm:
    sources:
      - demo.wat
    cmds:
      - wat2wasm demo.wat
  flash:
    desc: "Flash the demo to pybadge"
    cmds:
      - task: build-wasm
      - tinygo flash -size short -target pybadge .
